# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learnModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('postal', models.CharField(max_length=50)),
                ('alternateEmail', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
            ],
        ),
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=0)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('contentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=0)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavouriteCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logInTime', models.DateTimeField(verbose_name=b'time login')),
                ('logOutTime', models.DateTimeField(verbose_name=b'time logout')),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCorrect', models.BooleanField(default=0)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('choiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Choice')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Question')),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Quiz')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=0)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('TopicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Topic')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentCompleted', models.CharField(max_length=6)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='typeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserType'),
        ),
    ]
