# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161101_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontent',
            old_name='contentID',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='usercontent',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userfavouritecourse',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='userfavouritecourse',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlog',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userquiz',
            old_name='choiceID',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='userquiz',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='userquiz',
            old_name='quizID',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='userquiz',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertopic',
            old_name='TopicID',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='usertopic',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertrack',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usertrack',
            old_name='userID',
            new_name='user',
        ),
    ]
