# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161101_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='logInTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'time login'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='logOutTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'time logout'),
        ),
    ]
