# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0031_auto_20161115_1056'),
        ('users', '0010_auto_20161115_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavouriteCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfavourite',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userfavourite',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userfavourite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavourite',
        ),
    ]
