# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0032_auto_20161117_1114'),
        ('users', '0012_auto_20161115_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
