# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20161212_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='type',
            field=models.CharField(default='LC', max_length=5),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='type',
            field=models.CharField(default='LCR', max_length=5),
        ),
        migrations.AddField(
            model_name='userfavouritecontent',
            name='type',
            field=models.CharField(default='FC', max_length=5),
        ),
        migrations.AddField(
            model_name='userfavouritecourse',
            name='type',
            field=models.CharField(default='FCR', max_length=5),
        ),
        migrations.AddField(
            model_name='userfavouriteresource',
            name='type',
            field=models.CharField(default='FR', max_length=5),
        ),
        migrations.AddField(
            model_name='userresourcedownload',
            name='type',
            field=models.CharField(default='DR', max_length=5),
        ),
        migrations.AddField(
            model_name='usertopic',
            name='type',
            field=models.CharField(default='LT', max_length=5),
        ),
    ]
