# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0047_remove_checklist_ischecked'),
        ('users', '0020_auto_20161213_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isChecked', models.BooleanField(default=0)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('checkList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.CheckList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
