# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceText', models.CharField(max_length=250)),
                ('isAnswer', models.BooleanField(default=0)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('contentType', models.CharField(max_length=80)),
                ('imageURL', models.URLField()),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('contentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=250)),
                ('questionDescription', models.CharField(max_length=300)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
            ],
        ),
        migrations.CreateModel(
            name='TopicCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(verbose_name=b'date created')),
                ('updatedDate', models.DateTimeField(verbose_name=b'update created')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course')),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='questionquiz',
            name='quizID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Topic'),
        ),
        migrations.AddField(
            model_name='contenttopic',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Topic'),
        ),
        migrations.AddField(
            model_name='choice',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Question'),
        ),
    ]
