# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0002_auto_20161006_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicCourse',
            new_name='CourseTopic',
        ),
        migrations.RenameModel(
            old_name='QuestionQuiz',
            new_name='QuizQuestion',
        ),
        migrations.RenameModel(
            old_name='ContentTopic',
            new_name='TopicContent',
        ),
    ]
