# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0006_auto_20161012_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetopic',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='topicID',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='contentID',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='topicID',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='LanguageID',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='ResourceTypeID',
            new_name='ResourceType',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='sourceID',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='topicID',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='quizID',
            new_name='quiz',
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course'),
        ),
        migrations.DeleteModel(
            name='CourseTopic',
        ),
        migrations.DeleteModel(
            name='TopicContent',
        ),
    ]
