# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0007_auto_20161013_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='content',
            name='imageURL',
            field=models.ImageField(upload_to='Image/Content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='imageURL',
            field=models.ImageField(upload_to='Image/Course'),
        ),
    ]
