# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0009_auto_20161013_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to=b'Image/Article'),
        ),
    ]
