# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0010_article_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='audio_file',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video_file',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentType',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='content',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to=b'Image/Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Country'),
        ),
        migrations.AddField(
            model_name='content',
            name='informationFor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learnModule.InformationFor'),
        ),
    ]
