# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0013_auto_20161020_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='ResourceType',
            new_name='resourceType',
        ),
    ]
