# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0014_auto_20161020_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtowork',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
