# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0015_auto_20161020_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_content',
            field=models.FileField(blank=True, upload_to=b'Image/Content'),
        ),
    ]
