# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0016_content_file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to='Image/Article'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learnModule.ContentType'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file_content',
            field=models.FileField(blank=True, upload_to='Image/Content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to='Image/Content'),
        ),
        migrations.AlterField(
            model_name='howtowork',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to='Image/HowToWork'),
        ),
    ]
