# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0018_content_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='keywords',
            new_name='keywordsContent',
        ),
    ]
