# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0019_auto_20161021_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
