# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0020_auto_20161021_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexity',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
