# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0023_headermenu_submenulang'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=50, null=True)),
                ('aboutIRRG', models.CharField(blank=True, max_length=200, null=True)),
                ('aboutDeyahaha', models.CharField(blank=True, max_length=100, null=True)),
                ('partnerIns', models.CharField(blank=True, max_length=100, null=True)),
                ('supportedPartially', models.CharField(blank=True, max_length=200, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=200, null=True)),
                ('shortheading2', models.CharField(blank=True, max_length=80, null=True)),
                ('heading3', models.CharField(blank=True, max_length=500, null=True)),
                ('quickStarthead', models.CharField(blank=True, max_length=50, null=True)),
                ('cMemberTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('industryORGovTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('organizersTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('storiesTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('readMore', models.CharField(blank=True, max_length=50, null=True)),
                ('howitWorksHead', models.CharField(blank=True, max_length=50, null=True)),
                ('howitWorksButton1', models.CharField(blank=True, max_length=50, null=True)),
                ('howitWorksButton2', models.CharField(blank=True, max_length=50, null=True)),
                ('howitWorksButton3', models.CharField(blank=True, max_length=50, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.AlterField(
            model_name='submenulang',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
