# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0024_auto_20161102_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(blank=True, max_length=100, null=True)),
                ('industyOrGov', models.CharField(blank=True, max_length=200, null=True)),
                ('organizer', models.CharField(blank=True, max_length=200, null=True)),
                ('resources', models.CharField(blank=True, max_length=100, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LeftMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('multimedia', models.CharField(blank=True, max_length=200, null=True)),
                ('resources', models.CharField(blank=True, max_length=200, null=True)),
                ('help', models.CharField(blank=True, max_length=100, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=80, null=True)),
                ('writtenby', models.CharField(blank=True, max_length=50, null=True)),
                ('writtenfor', models.CharField(blank=True, max_length=200, null=True)),
                ('complexity', models.CharField(blank=True, max_length=200, null=True)),
                ('contentType', models.CharField(blank=True, max_length=200, null=True)),
                ('searchButton', models.CharField(blank=True, max_length=100, null=True)),
                ('allword', models.CharField(blank=True, max_length=100, null=True)),
                ('titleWord', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptionWord', models.CharField(blank=True, max_length=100, null=True)),
                ('topicWord', models.CharField(blank=True, max_length=100, null=True)),
                ('fileFormatWord', models.CharField(blank=True, max_length=100, null=True)),
                ('keywordsWord', models.CharField(blank=True, max_length=100, null=True)),
                ('copyrightInfoWord', models.CharField(blank=True, max_length=100, null=True)),
                ('resourcesWord', models.CharField(blank=True, max_length=100, null=True)),
                ('downloadWord', models.CharField(blank=True, max_length=100, null=True)),
                ('readPDFWord', models.CharField(blank=True, max_length=100, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.AlterField(
            model_name='submenulang',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
