# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0025_auto_20161102_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmenu',
            name='language',
        ),
        migrations.RemoveField(
            model_name='footermenu',
            name='language',
        ),
        migrations.RemoveField(
            model_name='headermenu',
            name='language',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='leftmenu',
            name='language',
        ),
        migrations.RemoveField(
            model_name='librarypage',
            name='language',
        ),
        migrations.DeleteModel(
            name='ContentMenu',
        ),
        migrations.DeleteModel(
            name='FooterMenu',
        ),
        migrations.DeleteModel(
            name='HeaderMenu',
        ),
        migrations.DeleteModel(
            name='IndexPage',
        ),
        migrations.DeleteModel(
            name='LeftMenu',
        ),
        migrations.DeleteModel(
            name='LibraryPage',
        ),
    ]
