# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0026_auto_20161104_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='codeFileName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
