# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0028_howtowork_srno'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lengthInMB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='sizeInPages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='srNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
