# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0030_topic_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtowork',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to=b'staticfiles/learnModule/images'),
        ),
    ]
