# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0031_auto_20161115_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to=b'staticfiles/learnModule/images'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file_content',
            field=models.FileField(blank=True, upload_to=b'staticfiles/learnModule/images'),
        ),
        migrations.AlterField(
            model_name='content',
            name='imageURL',
            field=models.ImageField(blank=True, upload_to=b'staticfiles/learnModule/images'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_file',
            field=models.FileField(blank=True, upload_to=b'staticfiles/learnModule/images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='imageURL',
            field=models.ImageField(upload_to=b'staticfiles/learnModule/images'),
        ),
    ]
