# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0032_auto_20161117_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contentFor',
            field=models.CharField(blank=True, choices=[(b'0', b'None'), (b'1', b'FPIC'), (b'2', b'Consultation')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
