# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0034_auto_20161118_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='highlight',
            field=models.CharField(choices=[(b'0', b'None'), (b'1', b'Information'), (b'2', b'Toolkit')], default=0, max_length=2),
        ),
    ]
