# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0036_complexity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=models.ForeignKey(default=59, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content'),
        ),
    ]
