# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0037_quiz_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='style',
            field=models.CharField(choices=[(b'0', b'None'), (b'1', b'Text'), (b'2', b'Text & Image'), (b'3', b'Quiz Boolean'), (b'4', b'Checklist'), (b'5', b'Quiz Multiple Choice'), (b'6', b'Summary'), (b'7', b'Resources'), (b'8', b'Finish'), (b'9', b'Other')], default=0, max_length=2),
        ),
    ]
