# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0038_content_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answerDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
