# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0039_choice_answerdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imageURL', models.ImageField(blank=True, null=True, upload_to=b'staticfiles/learnModule/images')),
                ('imageCaption', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='community',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Country'),
        ),
        migrations.AddField(
            model_name='article',
            name='involvedCompany',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='articlechild',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Article'),
        ),
        migrations.AddField(
            model_name='articlechild',
            name='language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language'),
        ),
    ]
