# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0040_auto_20161206_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='opinionBad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='opinionGood',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='opinionUnknown',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
