# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0043_auto_20161214_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course'),
        ),
        migrations.AddField(
            model_name='content',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learnModule.ContentStyle'),
        ),
    ]
