# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0044_auto_20161214_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNo', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('isChecked', models.BooleanField(default=0)),
                ('weightValue', models.IntegerField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Course')),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(blank=True, upload_to=b'staticfiles/learnModule/images')),
                ('congratWords', models.CharField(max_length=200)),
                ('suggestion', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content')),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Content')),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNo', models.IntegerField(blank=True, null=True)),
                ('advice', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learnModule.Language')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnModule.Summary')),
            ],
        ),
    ]
