# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0045_checklist_finish_summary_summarychild'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to=b'staticfiles/learnModule/images'),
        ),
    ]
