# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0046_summary_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='isChecked',
        ),
    ]
