# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnModule', '0047_remove_checklist_ischecked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='imageURL',
        ),
    ]
