# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161120_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/blog/images'),
        ),
    ]
