# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_story_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='country',
        ),
    ]
